"""
PostgreSQL Advanced Query Features (Phase 5.7).

This module contains advanced query execution components:
- query_timeout.py: Chainable query timeout with context manager
- explain.py: EXPLAIN/ANALYZE parsing and optimization
- pagination.py: Cursor-based and offset pagination
- prepared.py: Prepared statement caching
- cancel.py: Query cancellation and tracking
"""

from .query_timeout import (
    QueryTimeoutError as ChainQueryTimeoutError,
    QueryTimeout,
    TimeoutConfig,
    TimeoutStats as ChainTimeoutStats,
    TimeoutContext,
    timeout_context,
    TimeoutExecutor,
    TimeoutMixin,
    get_timeout_stats,
    reset_timeout_stats,
    get_current_timeout,
    set_current_timeout,
    create_timeout,
    create_timeout_executor,
)
from .explain import (
    ExplainFormat,
    NodeType,
    SuggestionSeverity,
    BufferStats,
    PlanNode,
    Suggestion,
    QueryPlan,
    PlanComparison,
    ExplainTextParser,
    PlanAnalyzer,
    ExplainMixin,
    ExplainExecutor,
)
from .pagination import (
    PaginationMethod,
    CursorDirection,
    PaginationConfig,
    Cursor,
    Page,
    OffsetPage,
    KeysetPaginator,
    OffsetPaginator,
    SmartPaginator,
    StreamingPaginator,
    PaginationMixin,
    get_pagination_config,
    set_pagination_config,
)
from .prepared import (
    StatementState,
    PreparedStats,
    PreparedStatement,
    PreparedCache,
    PreparedExecutor,
    prepared,
    SchemaWatcher,
    get_prepared_executor,
    set_prepared_executor,
)
from .cancel import (
    QueryState,
    CancelReason,
    CancellationConfig,
    RunningQuery,
    CancellationToken,
    QueryCancelledError,
    QueryTracker,
    QueryRegistry,
    CancelExecutor,
    get_current_tracker,
    set_current_tracker,
    get_query_registry,
    set_query_registry,
    track_query,
    cancel_queries,
    cancel,
    get_running_queries,
)

__all__ = [
    # Query Timeout (Chain)
    "ChainQueryTimeoutError",
    "QueryTimeout",
    "TimeoutConfig",
    "ChainTimeoutStats",
    "TimeoutContext",
    "timeout_context",
    "TimeoutExecutor",
    "TimeoutMixin",
    "get_timeout_stats",
    "reset_timeout_stats",
    "get_current_timeout",
    "set_current_timeout",
    "create_timeout",
    "create_timeout_executor",
    # Explain
    "ExplainFormat",
    "NodeType",
    "SuggestionSeverity",
    "BufferStats",
    "PlanNode",
    "Suggestion",
    "QueryPlan",
    "PlanComparison",
    "ExplainTextParser",
    "PlanAnalyzer",
    "ExplainMixin",
    "ExplainExecutor",
    # Pagination
    "PaginationMethod",
    "CursorDirection",
    "PaginationConfig",
    "Cursor",
    "Page",
    "OffsetPage",
    "KeysetPaginator",
    "OffsetPaginator",
    "SmartPaginator",
    "StreamingPaginator",
    "PaginationMixin",
    "get_pagination_config",
    "set_pagination_config",
    # Prepared
    "StatementState",
    "PreparedStats",
    "PreparedStatement",
    "PreparedCache",
    "PreparedExecutor",
    "prepared",
    "SchemaWatcher",
    "get_prepared_executor",
    "set_prepared_executor",
    # Cancel
    "QueryState",
    "CancelReason",
    "CancellationConfig",
    "RunningQuery",
    "CancellationToken",
    "QueryCancelledError",
    "QueryTracker",
    "QueryRegistry",
    "CancelExecutor",
    "get_current_tracker",
    "set_current_tracker",
    "get_query_registry",
    "set_query_registry",
    "track_query",
    "cancel_queries",
    "cancel",
    "get_running_queries",
]

