(function(g){'use strict';var t=new Map(),el=null,cfg={position:'bottom-right',max:3,dur:4e3,close:true};
var V={success:'border-green-500 bg-green-50 dark:bg-green-950',error:'border-red-500 bg-red-50 dark:bg-red-950',warning:'border-yellow-500 bg-yellow-50 dark:bg-yellow-950',info:'border-blue-500 bg-blue-50 dark:bg-blue-950'};
var I={success:'<svg class="h-5 w-5 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>',error:'<svg class="h-5 w-5 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>',warning:'<svg class="h-5 w-5 text-yellow-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/></svg>',info:'<svg class="h-5 w-5 text-blue-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>'};
function init(){el=document.querySelector('[data-pynext-toaster]');if(!el)return;var d=el.dataset;cfg={position:d.position||'bottom-right',max:parseInt(d.maxVisible)||3,dur:parseInt(d.duration)||4e3,close:d.closeButton!=='false'};el.addEventListener('click',function(e){var c=e.target.closest('[data-pynext-toast-close]');if(c){var to=c.closest('[data-pynext-toast]');if(to)dismiss(to.dataset.pynextToast)}var a=e.target.closest('[data-pynext-toast-action]');if(a){var to=a.closest('[data-pynext-toast]');if(to){var id=to.dataset.pynextToast,d=t.get(id);if(d&&d.cb)d.cb();dismiss(id)}}});el.addEventListener('mouseenter',pause);el.addEventListener('mouseleave',resume)}
function show(o){if(!el)return null;var id=o.id||'t'+Math.random().toString(36).substr(2,9),m=o.message||'',desc=o.description,v=o.variant||'default',dur=o.duration!==undefined?o.duration:cfg.dur,act=o.action;var vc=V[v]||'',ic=I[v]||'',ih=ic?'<div class="flex-shrink-0 mr-3">'+ic+'</div>':'',dh=desc?'<p class="text-sm text-muted-foreground mt-1">'+esc(desc)+'</p>':'',ah=act?'<button data-pynext-toast-action class="ml-4 text-sm font-medium underline">'+esc(act.label)+'</button>':'',ch=cfg.close?'<button data-pynext-toast-close class="ml-4 text-muted-foreground" aria-label="Close"><svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg></button>':'';var h='<div data-pynext-toast="'+id+'" class="relative flex items-center justify-between w-full max-w-md p-4 bg-background border rounded-lg shadow-lg pointer-events-auto animate-in slide-in-from-top-full fade-in-0 '+vc+'" role="alert">'+ih+'<div class="flex-1"><p class="text-sm font-medium">'+esc(m)+'</p>'+dh+'</div>'+ah+ch+'</div>';var w=document.createElement('div');w.innerHTML=h;var te=w.firstElementChild;cfg.position.startsWith('top')?el.appendChild(te):el.insertBefore(te,el.firstChild);var tm=dur>0?setTimeout(function(){dismiss(id)},dur):null;t.set(id,{el:te,tm:tm,dur:dur,rem:dur,pa:null,cb:act&&act.callback});enforce();return id}
function dismiss(id){var d=t.get(id);if(!d)return;if(d.tm)clearTimeout(d.tm);d.el.classList.add('animate-out','fade-out-0','slide-out-to-right-full');setTimeout(function(){d.el.remove();t.delete(id)},150)}
function dismissAll(){for(var id of t.keys())dismiss(id)}
function pause(){for(var[id,d]of t){if(d.tm){clearTimeout(d.tm);d.tm=null;d.pa=Date.now()}}}
function resume(){for(var[id,d]of t){if(d.pa&&d.rem>0){var r=Math.max(d.rem-(Date.now()-d.pa),0);if(r>0)d.tm=setTimeout(function(){dismiss(id)},r);d.rem=r;d.pa=null}}}
function enforce(){var a=Array.from(t.keys()),x=a.length-cfg.max;if(x>0){var r=cfg.position.startsWith('top')?a.slice(0,x):a.slice(-x);for(var id of r)dismiss(id)}}
function update(id,o){var d=t.get(id);if(!d)return;var e=d.el;if(o.message){var m=e.querySelector('.text-sm.font-medium');if(m)m.textContent=o.message}if(o.variant){var vc=V[o.variant]||'';e.dataset.variant=o.variant;Object.values(V).forEach(function(c){c.split(' ').forEach(function(x){x&&e.classList.remove(x)})});vc.split(' ').forEach(function(c){c&&e.classList.add(c)});var ic=e.querySelector('.flex-shrink-0');if(ic&&I[o.variant])ic.innerHTML=I[o.variant]}}
function esc(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML}
g.PyNextToast={show:show,dismiss:dismiss,dismissAll:dismissAll,update:update,success:function(m,o){return show(Object.assign({},o,{message:m,variant:'success'}))},error:function(m,o){return show(Object.assign({},o,{message:m,variant:'error'}))},warning:function(m,o){return show(Object.assign({},o,{message:m,variant:'warning'}))},info:function(m,o){return show(Object.assign({},o,{message:m,variant:'info'}))},promise:async function(p,o){var id=show({message:o.loading||'Loading...',variant:'default',duration:0});try{var r=await p;update(id,{message:typeof o.success==='function'?o.success(r):(o.success||'Success'),variant:'success'});setTimeout(function(){dismiss(id)},cfg.dur);return r}catch(e){update(id,{message:typeof o.error==='function'?o.error(e):(o.error||'Error'),variant:'error'});setTimeout(function(){dismiss(id)},cfg.dur);throw e}}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();document.addEventListener('turbo:load',init);document.addEventListener('htmx:afterSettle',init)})(window);

