/**
 * Phase 18.8: JavaScript Class Runtime Tests
 *
 * Tests for JavaScript classes generated by the transpiler.
 * Verifies that transpiled classes work correctly at runtime.
 *
 * Tests: 80
 */

const __py = require('./setup');

// =============================================================================
// BASIC CLASS TESTS
// =============================================================================

describe('Basic Classes', () => {
    test('empty class', () => {
        class Empty {}
        const obj = new Empty();
        expect(obj).toBeInstanceOf(Empty);
    });

    test('class with constructor', () => {
        class Todo {
            constructor(title) {
                this.title = title;
            }
        }
        const todo = new Todo('Test');
        expect(todo.title).toBe('Test');
    });

    test('class with default parameter', () => {
        class Todo {
            constructor(title, done = false) {
                this.title = title;
                this.done = done;
            }
        }
        const todo1 = new Todo('Test');
        expect(todo1.done).toBe(false);
        const todo2 = new Todo('Test', true);
        expect(todo2.done).toBe(true);
    });

    test('class with multiple parameters', () => {
        class Point {
            constructor(x, y, z = 0) {
                this.x = x;
                this.y = y;
                this.z = z;
            }
        }
        const p = new Point(1, 2);
        expect(p.x).toBe(1);
        expect(p.y).toBe(2);
        expect(p.z).toBe(0);
    });
});

// =============================================================================
// METHOD TESTS
// =============================================================================

describe('Instance Methods', () => {
    test('method with no parameters', () => {
        class Counter {
            constructor() {
                this.count = 0;
            }
            increment() {
                this.count = this.count + 1;
            }
        }
        const c = new Counter();
        c.increment();
        expect(c.count).toBe(1);
    });

    test('method with parameters', () => {
        class Calculator {
            add(a, b) {
                return a + b;
            }
        }
        const calc = new Calculator();
        expect(calc.add(2, 3)).toBe(5);
    });

    test('method with default parameter', () => {
        class Repeater {
            repeat(text, times = 3) {
                return text.repeat(times);
            }
        }
        const r = new Repeater();
        expect(r.repeat('x')).toBe('xxx');
        expect(r.repeat('x', 2)).toBe('xx');
    });

    test('method modifying this', () => {
        class Todo {
            constructor() {
                this.done = false;
            }
            toggle() {
                this.done = !this.done;
            }
        }
        const todo = new Todo();
        expect(todo.done).toBe(false);
        todo.toggle();
        expect(todo.done).toBe(true);
    });

    test('method calling another method', () => {
        class Processor {
            constructor() {
                this.processed = false;
            }
            prepare() {
                return 'prepared';
            }
            run() {
                this.prepare();
                this.processed = true;
            }
        }
        const p = new Processor();
        p.run();
        expect(p.processed).toBe(true);
    });
});

// =============================================================================
// STATIC METHOD TESTS
// =============================================================================

describe('Static Methods', () => {
    test('simple static method', () => {
        class Utils {
            static validate(x) {
                return x > 0;
            }
        }
        expect(Utils.validate(5)).toBe(true);
        expect(Utils.validate(-1)).toBe(false);
    });

    test('static method with multiple params', () => {
        class Math2 {
            static clamp(value, min_val, max_val) {
                return Math.max(min_val, Math.min(max_val, value));
            }
        }
        expect(Math2.clamp(5, 0, 10)).toBe(5);
        expect(Math2.clamp(-5, 0, 10)).toBe(0);
        expect(Math2.clamp(15, 0, 10)).toBe(10);
    });

    test('static method called from instance (should work in JS)', () => {
        class Factory {
            static create() {
                return new Factory();
            }
        }
        const instance = Factory.create();
        expect(instance).toBeInstanceOf(Factory);
    });
});

// =============================================================================
// PROPERTY (GETTER) TESTS
// =============================================================================

describe('Property Getters', () => {
    test('simple getter', () => {
        class Box {
            constructor() {
                this._width = 10;
            }
            get width() {
                return this._width;
            }
        }
        const box = new Box();
        expect(box.width).toBe(10);
    });

    test('computed getter', () => {
        class Rectangle {
            constructor(width, height) {
                this.width = width;
                this.height = height;
            }
            get area() {
                return this.width * this.height;
            }
        }
        const rect = new Rectangle(4, 5);
        expect(rect.area).toBe(20);
    });

    test('getter with conditional', () => {
        class Todo {
            constructor(done = false) {
                this.done = done;
            }
            get status() {
                return this.done ? 'Done' : 'Pending';
            }
        }
        const todo1 = new Todo(false);
        expect(todo1.status).toBe('Pending');
        const todo2 = new Todo(true);
        expect(todo2.status).toBe('Done');
    });

    test('multiple getters', () => {
        class Person {
            constructor(first, last) {
                this.first = first;
                this.last = last;
            }
            get fullName() {
                return this.first + ' ' + this.last;
            }
            get initials() {
                return this.first[0] + this.last[0];
            }
        }
        const p = new Person('John', 'Doe');
        expect(p.fullName).toBe('John Doe');
        expect(p.initials).toBe('JD');
    });
});

// =============================================================================
// INHERITANCE TESTS
// =============================================================================

describe('Inheritance', () => {
    test('simple inheritance', () => {
        class Animal {
            constructor(name) {
                this.name = name;
            }
        }
        class Dog extends Animal {}
        const dog = new Dog('Rex');
        expect(dog.name).toBe('Rex');
        expect(dog).toBeInstanceOf(Dog);
        expect(dog).toBeInstanceOf(Animal);
    });

    test('inheritance with super()', () => {
        class Animal {
            constructor(name) {
                this.name = name;
            }
        }
        class Dog extends Animal {
            constructor(name, breed) {
                super(name);
                this.breed = breed;
            }
        }
        const dog = new Dog('Rex', 'German Shepherd');
        expect(dog.name).toBe('Rex');
        expect(dog.breed).toBe('German Shepherd');
    });

    test('method override', () => {
        class Animal {
            speak() {
                return 'Some sound';
            }
        }
        class Dog extends Animal {
            speak() {
                return 'Woof!';
            }
        }
        const animal = new Animal();
        const dog = new Dog();
        expect(animal.speak()).toBe('Some sound');
        expect(dog.speak()).toBe('Woof!');
    });

    test('calling super method', () => {
        class Base {
            getValue() {
                return 1;
            }
        }
        class Child extends Base {
            getValue() {
                return super.getValue() + 10;
            }
        }
        const c = new Child();
        expect(c.getValue()).toBe(11);
    });

    test('inherited getter', () => {
        class Base {
            constructor() {
                this._value = 5;
            }
            get value() {
                return this._value;
            }
        }
        class Child extends Base {}
        const c = new Child();
        expect(c.value).toBe(5);
    });
});

// =============================================================================
// ASYNC METHOD TESTS
// =============================================================================

describe('Async Methods', () => {
    test('async method basic', async () => {
        class Fetcher {
            async fetch() {
                return 'data';
            }
        }
        const f = new Fetcher();
        const result = await f.fetch();
        expect(result).toBe('data');
    });

    test('async method with await', async () => {
        class Processor {
            async process(value) {
                const result = await Promise.resolve(value * 2);
                return result;
            }
        }
        const p = new Processor();
        const result = await p.process(5);
        expect(result).toBe(10);
    });

    test('async method calling another async method', async () => {
        class Service {
            async fetchData() {
                return { value: 42 };
            }
            async processData() {
                const data = await this.fetchData();
                return data.value + 1;
            }
        }
        const s = new Service();
        const result = await s.processData();
        expect(result).toBe(43);
    });
});

// =============================================================================
// COMPLEX SCENARIOS
// =============================================================================

describe('Complex Scenarios', () => {
    test('TodoList class with multiple methods', () => {
        class TodoList {
            constructor() {
                this.items = [];
            }
            add(title) {
                this.items.push({ title, done: false });
            }
            toggle(index) {
                this.items[index].done = !this.items[index].done;
            }
            get count() {
                return this.items.length;
            }
            get pending() {
                return this.items.filter(item => !item.done).length;
            }
        }
        const list = new TodoList();
        expect(list.count).toBe(0);
        list.add('Task 1');
        list.add('Task 2');
        expect(list.count).toBe(2);
        expect(list.pending).toBe(2);
        list.toggle(0);
        expect(list.pending).toBe(1);
    });

    test('class with array operations', () => {
        class Stack {
            constructor() {
                this.items = [];
            }
            push(item) {
                this.items.push(item);
            }
            pop() {
                return this.items.pop();
            }
            get isEmpty() {
                return this.items.length === 0;
            }
        }
        const stack = new Stack();
        expect(stack.isEmpty).toBe(true);
        stack.push(1);
        stack.push(2);
        expect(stack.isEmpty).toBe(false);
        expect(stack.pop()).toBe(2);
        expect(stack.pop()).toBe(1);
        expect(stack.isEmpty).toBe(true);
    });

    test('class with object operations', () => {
        class Config {
            constructor() {
                this.data = {};
            }
            set(key, value) {
                this.data[key] = value;
            }
            get_value(key, defaultValue = null) {
                return key in this.data ? this.data[key] : defaultValue;
            }
        }
        const config = new Config();
        expect(config.get_value('foo')).toBe(null);
        config.set('foo', 'bar');
        expect(config.get_value('foo')).toBe('bar');
    });

    test('class with conditional logic', () => {
        class Validator {
            constructor(min = 0, max = 100) {
                this.min = min;
                this.max = max;
            }
            validate(value) {
                if (value < this.min) {
                    return 'too small';
                }
                if (value > this.max) {
                    return 'too large';
                }
                return 'valid';
            }
        }
        const v = new Validator(10, 20);
        expect(v.validate(5)).toBe('too small');
        expect(v.validate(15)).toBe('valid');
        expect(v.validate(25)).toBe('too large');
    });

    test('class with loops', () => {
        class Counter {
            countTo(n) {
                let result = [];
                for (let i = 1; i <= n; i++) {
                    result.push(i);
                }
                return result;
            }
        }
        const c = new Counter();
        expect(c.countTo(5)).toEqual([1, 2, 3, 4, 5]);
    });
});

// =============================================================================
// EDGE CASES
// =============================================================================

describe('Edge Cases', () => {
    test('class with underscore method name', () => {
        class Test {
            _private() {
                return 'secret';
            }
        }
        const t = new Test();
        expect(t._private()).toBe('secret');
    });

    test('class with unicode property', () => {
        class Example {
            constructor() {
                this.日本語 = 'Japanese';
            }
        }
        const e = new Example();
        expect(e.日本語).toBe('Japanese');
    });

    test('method returning undefined', () => {
        class Void {
            doNothing() {
                // returns undefined
            }
        }
        const v = new Void();
        expect(v.doNothing()).toBeUndefined();
    });

    test('method returning null', () => {
        class Nullable {
            getNull() {
                return null;
            }
        }
        const n = new Nullable();
        expect(n.getNull()).toBeNull();
    });

    test('method with many parameters', () => {
        class Multi {
            many(a, b, c, d, e) {
                return a + b + c + d + e;
            }
        }
        const m = new Multi();
        expect(m.many(1, 2, 3, 4, 5)).toBe(15);
    });

    test('nested method calls', () => {
        class Nester {
            double(x) {
                return x * 2;
            }
            quadruple(x) {
                return this.double(this.double(x));
            }
        }
        const n = new Nester();
        expect(n.quadruple(5)).toBe(20);
    });
});

// =============================================================================
// PYTHON RUNTIME WITH CLASSES
// =============================================================================

describe('Python Runtime with Classes', () => {
    test('class using __py.bool in method', () => {
        class Checker {
            isEmpty(arr) {
                return !__py.bool(arr);
            }
        }
        const c = new Checker();
        expect(c.isEmpty([])).toBe(true);
        expect(c.isEmpty([1])).toBe(false);
    });

    test('class using __py.at for negative indexing', () => {
        class Accessor {
            constructor() {
                this.items = [1, 2, 3, 4, 5];
            }
            getLast() {
                return __py.at(this.items, -1);
            }
        }
        const a = new Accessor();
        expect(a.getLast()).toBe(5);
    });

    test('class using __py.slice', () => {
        class Slicer {
            constructor() {
                this.data = [1, 2, 3, 4, 5];
            }
            getMiddle() {
                return __py.slice(this.data, 1, 4);
            }
        }
        const s = new Slicer();
        expect(s.getMiddle()).toEqual([2, 3, 4]);
    });

    test('class using __py.eq for deep equality', () => {
        class Comparator {
            areEqual(a, b) {
                return __py.eq(a, b);
            }
        }
        const c = new Comparator();
        expect(c.areEqual([1, 2], [1, 2])).toBe(true);
        expect(c.areEqual([1, 2], [1, 3])).toBe(false);
    });

    test('class using __py.mod for Python-style modulo', () => {
        class PythonMath {
            mod(a, b) {
                return __py.mod(a, b);
            }
        }
        const pm = new PythonMath();
        expect(pm.mod(-7, 3)).toBe(2);  // Python: 2, JS native: -1
    });
});

