"""
PyNext Transpiler - Stack Trace Rewriter (Phase 33.3)

=============================================================================
WHAT THIS FILE DOES
=============================================================================

Parses JavaScript stack traces and rewrites them to show original Python
source locations using source maps. Supports all major browser formats
(Chrome, Firefox, Safari, Edge).

=============================================================================
WHY THIS EXISTS (Problem It Solves)
=============================================================================

When Python code is transpiled to JavaScript and errors occur, the browser
shows JavaScript stack traces with JS file names and line numbers. This is
confusing for developers who wrote Python code.

This module:
1. Parses JavaScript stack traces (various browser formats)
2. Maps JavaScript positions to Python using source maps
3. Rewrites stack traces to show Python source locations
4. Preserves variable names from source maps

Example:
    JavaScript stack trace:
        Error: Division by zero
            at divide (handler.js:15:8)
            at calculate (handler.js:23:4)
    
    Rewritten to Python:
        Error: Division by zero
            at divide (handler.py:12:5)
            at calculate (handler.py:20:3)

=============================================================================
HOW IT WORKS (Architecture)
=============================================================================

    JavaScript Stack Trace          Parser              Source Map          Rewritten Stack
    ──────────────────────          ──────              ──────────          ───────────────
    at func (file.js:10:5)  →     Parse frame  →      Lookup mapping  →   at func (file.py:8:3)
    at main (file.js:20:2)  →     Parse frame  →      Lookup mapping  →   at main (file.py:18:1)

The rewriter:
1. Parses stack trace into frames (file, line, column, function)
2. Loads source map for each file
3. Looks up Python position for each JS position
4. Rewrites frame with Python location
5. Preserves function names and error messages

=============================================================================
WHO USES THIS
=============================================================================

- Browser DevTools: Shows Python stack traces instead of JS
- Error handlers: Rewrite errors before displaying to users
- Debug tools: Show Python locations in debug output
- Testing frameworks: Show Python locations in test failures

=============================================================================
WHEN THIS IS USED
=============================================================================

- At runtime: When JavaScript errors occur in transpiled code
- In DevTools: When viewing stack traces
- In error handlers: When catching and reporting errors
- In tests: When test failures occur

=============================================================================
WHERE THIS FITS
=============================================================================

Part of the source map system (pynext/transpiler/stack_rewriter.py).
Uses source maps generated by sourcemap.py.

=============================================================================
EXAMPLES
=============================================================================

Example usage:
    from pynext.transpiler.stack_rewriter import rewrite_stack_trace
    
    # JavaScript stack trace
    js_stack = (
        "Error: Division by zero\\n"
        "    at divide (handler.js:15:8)\\n"
        "    at calculate (handler.js:23:4)\\n"
        "    at main (handler.js:30:1)\\n"
    )
    
    # Source map (from sourcemap.py)
    source_map = {
        "version": 3,
        "sources": ["handler.py"],
        "mappings": "AAAA;AACA;..."
    }
    
    # Rewrite to Python
    python_stack = rewrite_stack_trace(js_stack, source_map)
    # Result:
    # Error: Division by zero
    #     at divide (handler.py:12:5)
    #     at calculate (handler.py:20:3)
    #     at main (handler.py:27:1)

=============================================================================
EDGE CASES
=============================================================================

- Missing source maps: Return original stack trace with warning
- Unmapped positions: Use closest mapped position or original
- Multiple source files: Handle each file's source map separately
- Minified code: Variable names preserved from source maps
- Anonymous functions: Track by position instead of name
- Nested functions: Preserve function hierarchy

=============================================================================
RELATED FILES
=============================================================================

- sourcemap.py: Generates source maps used by rewriter
- emitter.py: Emits code with source map tracking
- debug.py: Uses rewriter for debug output
"""

from __future__ import annotations
import re
import json
from typing import Optional, List, Dict, Tuple
from dataclasses import dataclass


@dataclass
class StackFrame:
    """
    A single stack frame from a stack trace.
    
    WHAT: Represents one frame in a stack trace.
    WHY: Enables parsing and rewriting of stack traces.
    HOW: Stores file, line, column, and function name.
    WHO: Created by stack trace parser.
    WHEN: When parsing JavaScript stack traces.
    WHERE: Part of stack trace rewriting.
    
    Attributes:
        function: Function name (or None for anonymous)
        file: Source file path
        line: Line number (1-indexed)
        column: Column number (1-indexed, optional)
        raw: Original frame string (for preservation)
    """
    function: Optional[str] = None
    file: Optional[str] = None
    line: Optional[int] = None
    column: Optional[int] = None
    raw: str = ""


@dataclass
class ParsedStackTrace:
    """
    A parsed stack trace with error message and frames.
    
    WHAT: Complete parsed stack trace structure.
    WHY: Enables structured rewriting of stack traces.
    HOW: Stores error message and list of frames.
    WHO: Created by stack trace parser.
    WHEN: When parsing complete stack traces.
    WHERE: Part of stack trace rewriting.
    
    Attributes:
        error_message: Error message (first line)
        frames: List of stack frames
        original: Original stack trace string
    """
    error_message: str = ""
    frames: List[StackFrame] = None
    original: str = ""
    
    def __post_init__(self):
        if self.frames is None:
            self.frames = []


class SourceMapLookup:
    """
    Fast lookup for source map positions (Phase 33.3).
    
    WHAT: Provides efficient position lookup in source maps.
    WHY: Source maps use VLQ encoding which is slow to decode repeatedly.
    HOW: Pre-decodes mappings into a lookup table and indexes function boundaries.
    WHO: Used by stack trace rewriter.
    WHEN: When rewriting stack traces.
    WHERE: Part of stack trace rewriting.
    
    The lookup table maps (gen_line, gen_col) → (src_line, src_col, name).
    
    Phase 33.3: Enhanced with multi-tier lookup strategy:
    1. Exact mapping match (O(1))
    2. Closest column on same line (O(n) where n = mappings on line)
    3. Closest mapping on any line (O(m) where m = total mappings)
    4. Function boundary interpolation (O(f) where f = functions, typically small)
    """
    
    def __init__(self, source_map: dict):
        """
        Initialize source map lookup.
        
        Phase 33.3: Indexes function boundaries for robust position lookup.
        This enables accurate mapping even when no exact mappings exist.
        
        Args:
            source_map: V3 source map dictionary
        """
        self.source_map = source_map
        self._lookup: Dict[Tuple[int, int], Tuple[int, int, Optional[str]]] = {}
        self._names = source_map.get("names", [])
        self._sources = source_map.get("sources", [])
        self._source_content = source_map.get("sourcesContent", [])
        
        # Phase 33.3: Index function boundaries for robust lookup
        # Function boundaries are stored as line numbers (integers) in the format:
        # {"generated": {"start": line, "end": line}, "source": {"start": line, "end": line}}
        self._function_index: List[Dict] = []
        functions = source_map.get("x_pynext_functions", [])
        for func in functions:
            try:
                # Extract line numbers (boundaries are line-only, not column)
                gen_start_line = func["generated"]["start"]
                gen_end_line = func["generated"]["end"]
                src_start_line = func["source"]["start"]
                src_end_line = func["source"]["end"]
                
                # Handle both integer and tuple/list formats (for robustness)
                # If it's a tuple/list, take the first element (line number)
                if isinstance(gen_start_line, (list, tuple)):
                    gen_start_line = gen_start_line[0] if len(gen_start_line) > 0 else 0
                if isinstance(gen_end_line, (list, tuple)):
                    gen_end_line = gen_end_line[0] if len(gen_end_line) > 0 else 0
                if isinstance(src_start_line, (list, tuple)):
                    src_start_line = src_start_line[0] if len(src_start_line) > 0 else 0
                if isinstance(src_end_line, (list, tuple)):
                    src_end_line = src_end_line[0] if len(src_end_line) > 0 else 0
                
                # Ensure they're integers
                gen_start_line = int(gen_start_line)
                gen_end_line = int(gen_end_line)
                src_start_line = int(src_start_line)
                src_end_line = int(src_end_line)
                
                # Validate boundaries (end must be >= start)
                if gen_end_line < gen_start_line or src_end_line < src_start_line:
                    continue  # Skip invalid boundaries
                
                self._function_index.append({
                    "name": func["name"],
                    "gen_start_line": gen_start_line,
                    "gen_end_line": gen_end_line,
                    "src_start_line": src_start_line,
                    "src_end_line": src_end_line,
                })
            except (KeyError, ValueError, TypeError, IndexError):
                # Skip functions with invalid boundary format
                continue
        
        # Decode mappings into lookup table
        self._build_lookup()
    
    def _build_lookup(self) -> None:
        """Build lookup table from VLQ-encoded mappings."""
        mappings_str = self.source_map.get("mappings", "")
        if not mappings_str:
            return
        
        # Decode VLQ mappings
        lines = mappings_str.split(";")
        gen_line = 0
        prev_gen_col = 0
        prev_src_idx = 0
        prev_src_line = 0
        prev_src_col = 0
        prev_name_idx = 0
        
        for line_segments in lines:
            if not line_segments:
                gen_line += 1
                continue
            
            gen_col = 0
            segments = line_segments.split(",")
            
            for segment in segments:
                if not segment:
                    continue
                
                # Decode VLQ segment
                values = self._decode_vlq_segment(segment)
                if len(values) < 4:
                    continue
                
                # Delta-decode
                gen_col += values[0]
                src_idx = prev_src_idx + values[1] if len(values) > 1 else prev_src_idx
                src_line = prev_src_line + values[2] if len(values) > 2 else prev_src_line
                src_col = prev_src_col + values[3] if len(values) > 3 else prev_src_col
                name_idx = None
                
                if len(values) > 4:
                    name_idx = prev_name_idx + values[4]
                
                # Store in lookup (use closest column if exact match not found)
                # We store multiple columns per line for closest-match lookup
                key = (gen_line, gen_col)
                name = self._names[name_idx] if name_idx is not None and name_idx < len(self._names) else None
                self._lookup[key] = (src_line, src_col, name)
                
                # Update previous values
                prev_gen_col = gen_col
                prev_src_idx = src_idx
                prev_src_line = src_line
                prev_src_col = src_col
                if name_idx is not None:
                    prev_name_idx = name_idx
            
            gen_line += 1
            prev_gen_col = 0  # Reset column at line start
    
    def _decode_vlq_segment(self, segment: str) -> List[int]:
        """Decode a VLQ segment into a list of integers."""
        # VLQ decoding implementation
        # This is the reverse of the encoding in sourcemap.py
        _VLQ_BASE = 32
        _VLQ_BASE_MASK = _VLQ_BASE - 1
        _VLQ_CONTINUATION_BIT = _VLQ_BASE
        _VLQ_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
        
        char_to_value = {char: i for i, char in enumerate(_VLQ_CHARS)}
        
        values = []
        current_value = None
        shift = 0
        
        for char in segment:
            if char not in char_to_value:
                continue
            
            digit = char_to_value[char]
            continuation = bool(digit & _VLQ_CONTINUATION_BIT)
            digit &= _VLQ_BASE_MASK
            
            if current_value is None:
                current_value = digit
            else:
                current_value |= digit << shift
            
            shift += 5
            
            if not continuation:
                # Zigzag decode
                if current_value & 1:
                    current_value = -(current_value >> 1)
                else:
                    current_value = current_value >> 1
                
                values.append(current_value)
                current_value = None
                shift = 0
        
        return values
    
    def lookup(self, gen_line: int, gen_col: int) -> Optional[Tuple[int, int, Optional[str]]]:
        """
        Look up Python position for JavaScript position.
        
        WHAT: Maps JavaScript position to Python position using multi-tier lookup.
        WHY: Enables rewriting stack traces with accurate Python locations.
        HOW: Uses 4-tier lookup strategy for robust position mapping.
        WHO: Called by stack trace rewriter.
        WHEN: For each frame in stack trace.
        WHERE: Part of position mapping.
        
        Phase 33.3: Multi-tier lookup strategy:
        1. Exact mapping match (O(1)) - fastest
        2. Closest column on same line (O(n) where n = mappings on line)
        3. Closest mapping on any line (O(m) where m = total mappings)
        4. Function boundary interpolation (O(f) where f = functions) - most robust
        
        Args:
            gen_line: Generated JavaScript line (0-indexed)
            gen_col: Generated JavaScript column (0-indexed)
        
        Returns:
            Tuple of (src_line, src_col, name) or None if not found
        """
        # Phase 33.3: Defensive guard for invalid positions
        # Line and column must be non-negative for valid source map lookups
        if gen_line < 0 or gen_col < 0:
            return None
        
        # Tier 1: Exact match (O(1) - fastest)
        key = (gen_line, gen_col)
        if key in self._lookup:
            return self._lookup[key]
        
        # Tier 2: Closest column on same line (O(n) where n = mappings on line)
        closest_same_line = None
        min_distance_same_line = float('inf')
        
        for (line, col), value in self._lookup.items():
            if line == gen_line:
                distance = abs(col - gen_col)
                if distance < min_distance_same_line:
                    min_distance_same_line = distance
                    closest_same_line = value
        
        if closest_same_line is not None:
            return closest_same_line
        
        # Tier 3: Closest mapping on any line (O(m) where m = total mappings)
        # This handles cases where there are no mappings on the target line
        closest_any_line = None
        min_distance_any_line = float('inf')
        
        for (line, col), value in self._lookup.items():
            # Use Manhattan distance (line difference + column difference)
            # Weight line distance more heavily than column distance
            line_distance = abs(line - gen_line) * 1000  # Weight lines more
            col_distance = abs(col - gen_col)
            total_distance = line_distance + col_distance
            
            if total_distance < min_distance_any_line:
                min_distance_any_line = total_distance
                closest_any_line = value
        
        # Tier 4: Function boundary interpolation (O(f) where f = functions)
        # This is the most robust fallback - uses function boundaries to interpolate
        function_match = self._lookup_function_boundary(gen_line, gen_col)
        if function_match:
            return function_match
        
        # If we have a closest mapping from Tier 3, use it
        if closest_any_line is not None:
            return closest_any_line
        
        return None
    
    def _lookup_function_boundary(
        self, 
        gen_line: int, 
        gen_col: int
    ) -> Optional[Tuple[int, int, Optional[str]]]:
        """
        Look up position using function boundaries with interpolation.
        
        WHAT: Maps positions within function boundaries using proportional interpolation.
        WHY: Provides accurate mapping even when no exact mappings exist.
        HOW: Finds containing function, then interpolates position proportionally.
        WHO: Used as Tier 4 fallback in lookup().
        WHEN: When no exact or close mappings are found.
        WHERE: Part of robust position lookup.
        
        Algorithm:
        1. Find function that contains (gen_line, gen_col)
        2. Calculate relative position within function (0.0 to 1.0)
        3. Interpolate to source position proportionally
        4. Return interpolated position with function name
        
        Note: Function boundaries are stored as line numbers only (not columns),
        so we use line-based interpolation. Column is preserved from the lookup
        or set to 0 if not available.
        
        Args:
            gen_line: Generated JavaScript line (0-indexed)
            gen_col: Generated JavaScript column (0-indexed)
        
        Returns:
            Tuple of (src_line, src_col, function_name) or None
        """
        for func in self._function_index:
            gen_start_line = func["gen_start_line"]
            gen_end_line = func["gen_end_line"]
            src_start_line = func["src_start_line"]
            src_end_line = func["src_end_line"]
            
            # Check if position is within function boundaries (line-based)
            # Inclusive start, exclusive end (standard for ranges)
            # Note: We only check lines since boundaries are line-only
            if gen_start_line <= gen_line < gen_end_line:
                # Position is within function - interpolate
                gen_total_lines = gen_end_line - gen_start_line
                
                if gen_total_lines == 0:
                    # Function is a single line - use start position
                    return (src_start_line, 0, func["name"])
                
                # Calculate relative position (0.0 to 1.0) based on line
                line_offset = gen_line - gen_start_line
                line_ratio = line_offset / gen_total_lines
                
                # Apply interpolation to source positions
                src_total_lines = src_end_line - src_start_line
                src_line = src_start_line + int(line_ratio * src_total_lines)
                
                # For column, we use the original gen_col (preserved from lookup)
                # or 0 if not meaningful. This is reasonable since we're doing
                # line-based interpolation and column precision isn't available.
                src_col = gen_col  # Preserve column from original position
                
                return (src_line, src_col, func["name"])
        
        return None


# =============================================================================
# STACK TRACE PARSING
# =============================================================================

def parse_stack_trace(stack_trace: str) -> ParsedStackTrace:
    """
    Parse a JavaScript stack trace into structured format.
    
    WHAT: Converts string stack trace to structured format.
    WHY: Enables programmatic rewriting of stack traces.
    HOW: Uses regex to parse different browser formats.
    WHO: Called by rewrite_stack_trace.
    WHEN: When processing JavaScript stack traces.
    WHERE: Part of stack trace rewriting.
    
    Supports formats:
    - Chrome/Edge: "at functionName (file.js:10:5)"
    - Firefox: "functionName@file.js:10:5"
    - Safari: "functionName@file.js:10:5" or "global code@file.js:10:5"
    - Node.js: "at functionName (file.js:10:5)"
    
    Args:
        stack_trace: JavaScript stack trace string
    
    Returns:
        ParsedStackTrace with error message and frames
    """
    lines = stack_trace.strip().split("\n")
    if not lines:
        return ParsedStackTrace(original=stack_trace)
    
    # First line is usually the error message
    error_message = lines[0]
    frames = []
    
    # Parse frames (skip first line)
    for line in lines[1:]:
        line = line.strip()
        if not line:
            continue
        
        frame = _parse_frame(line)
        if frame:
            frames.append(frame)
    
    return ParsedStackTrace(
        error_message=error_message,
        frames=frames,
        original=stack_trace,
    )


def _parse_frame(line: str) -> Optional[StackFrame]:
    """
    Parse a single stack frame line.
    
    WHAT: Extracts frame information from a stack trace line.
    WHY: Enables parsing of different browser formats.
    HOW: Uses regex patterns for Chrome, Firefox, Safari formats.
    WHO: Called by parse_stack_trace.
    WHEN: For each frame line in stack trace.
    WHERE: Part of stack trace parsing.
    
    Args:
        line: Stack frame line string
    
    Returns:
        StackFrame or None if line doesn't match any format
    """
    # Chrome/Edge/Node.js format: "at functionName (file.js:10:5)"
    # Handle URLs with colons: match file path up to the last colon before line number
    chrome_pattern = r"at\s+(?P<function>\S+)\s+\((?P<file>.+?):(?P<line>\d+):(?P<column>\d+)\)"
    match = re.search(chrome_pattern, line)
    if match:
        return StackFrame(
            function=match.group("function"),
            file=match.group("file"),
            line=int(match.group("line")),
            column=int(match.group("column")),
            raw=line,
        )
    
    # Firefox/Safari format: "functionName@file.js:10:5"
    # Handle URLs with colons
    firefox_pattern = r"(?P<function>[^@]+)@(?P<file>.+?):(?P<line>\d+):(?P<column>\d+)"
    match = re.search(firefox_pattern, line)
    if match:
        function = match.group("function").strip()
        if function == "global code":
            function = None
        return StackFrame(
            function=function if function else None,
            file=match.group("file"),
            line=int(match.group("line")),
            column=int(match.group("column")),
            raw=line,
        )
    
    # Chrome format without column: "at functionName (file.js:10)"
    chrome_no_col_pattern = r"at\s+(?P<function>\S+)\s+\((?P<file>.+?):(?P<line>\d+)\)"
    match = re.search(chrome_no_col_pattern, line)
    if match:
        return StackFrame(
            function=match.group("function"),
            file=match.group("file"),
            line=int(match.group("line")),
            column=None,
            raw=line,
        )
    
    # Firefox format without column: "functionName@file.js:10"
    firefox_no_col_pattern = r"(?P<function>[^@]+)@(?P<file>.+?):(?P<line>\d+)"
    match = re.search(firefox_no_col_pattern, line)
    if match:
        function = match.group("function").strip()
        if function == "global code":
            function = None
        return StackFrame(
            function=function if function else None,
            file=match.group("file"),
            line=int(match.group("line")),
            column=None,
            raw=line,
        )
    
    # Handle async functions: "at async functionName (file.js:10:5)"
    chrome_async_pattern = r"at\s+async\s+(?P<function>\S+)\s+\((?P<file>.+?):(?P<line>\d+):(?P<column>\d+)\)"
    match = re.search(chrome_async_pattern, line)
    if match:
        return StackFrame(
            function=match.group("function"),
            file=match.group("file"),
            line=int(match.group("line")),
            column=int(match.group("column")),
            raw=line,
        )
    
    # Handle negative line numbers (edge case, but parse anyway)
    chrome_neg_pattern = r"at\s+(?P<function>\S+)\s+\((?P<file>.+?):(?P<line>-?\d+):(?P<column>-?\d+)\)"
    match = re.search(chrome_neg_pattern, line)
    if match:
        return StackFrame(
            function=match.group("function"),
            file=match.group("file"),
            line=int(match.group("line")),
            column=int(match.group("column")),
            raw=line,
        )
    
    return None


# =============================================================================
# STACK TRACE REWRITING
# =============================================================================

def rewrite_stack_trace(
    stack_trace: str,
    source_map: dict,
    source_file: Optional[str] = None,
) -> str:
    """
    Rewrite a JavaScript stack trace to show Python source locations.
    
    WHAT: Converts JavaScript stack trace to Python stack trace.
    WHY: Enables developers to debug Python code in browser.
    HOW: Parses JS stack, maps positions using source map, rewrites frames.
    WHO: Used by error handlers and debug tools.
    WHEN: When JavaScript errors occur in transpiled code.
    WHERE: Part of stack trace rewriting system.
    
    Args:
        stack_trace: JavaScript stack trace string
        source_map: V3 source map dictionary
        source_file: Optional Python source file name (if not in source map)
    
    Returns:
        Rewritten stack trace with Python locations
    
    Example:
        js_stack = "Error: Division by zero\\n    at divide (handler.js:15:8)"
        source_map = {...}  # From sourcemap.py
        python_stack = rewrite_stack_trace(js_stack, source_map)
        # → "Error: Division by zero\\n    at divide (handler.py:12:5)"
    """
    parsed = parse_stack_trace(stack_trace)
    if not parsed.frames:
        return stack_trace  # No frames to rewrite
    
    lookup = SourceMapLookup(source_map)
    
    # Get source file name
    if not source_file:
        sources = source_map.get("sources", [])
        source_file = sources[0] if sources else "source.py"
    
    # Rewrite frames
    rewritten_lines = [parsed.error_message]
    
    for frame in parsed.frames:
        if not frame.file or not frame.line:
            # Can't rewrite without file/line
            rewritten_lines.append(frame.raw)
            continue
        
        # Convert to 0-indexed for lookup
        gen_line = frame.line - 1
        gen_col = (frame.column - 1) if frame.column else 0
        
        # Phase 33.3: Handle zero/negative line numbers gracefully
        # Line 0 (1-indexed) becomes -1 (0-indexed), which is invalid
        # Negative line numbers are also invalid
        if gen_line < 0:
            rewritten_lines.append(frame.raw)  # Preserve original frame
            continue
        
        # Look up Python position
        mapped = lookup.lookup(gen_line, gen_col)
        
        if mapped:
            src_line, src_col, name = mapped
            # Convert back to 1-indexed
            src_line += 1
            src_col += 1
            
            # Use mapped function name if available, otherwise original
            function_name = name if name else frame.function
            
            # Rewrite frame
            if function_name:
                rewritten_lines.append(f"    at {function_name} ({source_file}:{src_line}:{src_col})")
            else:
                rewritten_lines.append(f"    at {source_file}:{src_line}:{src_col}")
        else:
            # No mapping found, use original
            rewritten_lines.append(frame.raw)
    
    return "\n".join(rewritten_lines)


def rewrite_stack_trace_from_file(
    stack_trace: str,
    source_map_path: str,
    source_file: Optional[str] = None,
) -> str:
    """
    Rewrite stack trace using source map from file.
    
    WHAT: Convenience function to load source map from file.
    WHY: Simplifies usage when source map is in a file.
    HOW: Loads source map JSON and calls rewrite_stack_trace.
    WHO: Used by error handlers that have source map files.
    WHEN: When source map is stored as a file.
    WHERE: Part of stack trace rewriting API.
    
    Args:
        stack_trace: JavaScript stack trace string
        source_map_path: Path to source map JSON file
        source_file: Optional Python source file name
    
    Returns:
        Rewritten stack trace with Python locations
    """
    try:
        with open(source_map_path, "r") as f:
            source_map = json.load(f)
        return rewrite_stack_trace(stack_trace, source_map, source_file)
    except Exception as e:
        # Return original if source map can't be loaded
        return stack_trace

