"""
Edge Adapters - Platform-Specific Implementations

Adapters for different edge platforms that handle
request/response translation and binding access.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional, Tuple

from .detector import EdgePlatform


class EdgeAdapter(ABC):
    """
    Base adapter for edge platforms.
    
    Subclasses implement platform-specific logic.
    """
    
    platform: EdgePlatform
    
    @abstractmethod
    def translate_request(self, raw_request: Any) -> Dict[str, Any]:
        """
        Translate platform request to standard format.
        
        Args:
            raw_request: Platform-specific request object
            
        Returns:
            Standardized request dict
        """
        pass
    
    @abstractmethod
    def translate_response(self, response: Dict[str, Any]) -> Any:
        """
        Translate standard response to platform format.
        
        Args:
            response: Standardized response dict
            
        Returns:
            Platform-specific response object
        """
        pass
    
    @abstractmethod
    def get_bindings(self, env: Any) -> Dict[str, Any]:
        """
        Extract bindings from environment.
        
        Args:
            env: Platform environment object
            
        Returns:
            Dict of named bindings
        """
        pass
    
    @abstractmethod
    def generate_entry_point(
        self,
        handler: Callable,
        config: Dict[str, Any],
    ) -> str:
        """
        Generate platform-specific entry point code.
        
        Args:
            handler: The handler function
            config: Edge configuration
            
        Returns:
            JavaScript code string
        """
        pass
    
    def generate_config(self, config: Dict[str, Any]) -> str:
        """
        Generate platform configuration file.
        
        Args:
            config: Edge configuration
            
        Returns:
            Configuration file content
        """
        return ""


class CloudflareAdapter(EdgeAdapter):
    """Adapter for Cloudflare Workers."""
    
    platform = EdgePlatform.CLOUDFLARE
    
    def translate_request(self, raw_request: Any) -> Dict[str, Any]:
        """Translate Cloudflare Request to standard format."""
        return {
            "method": raw_request.method,
            "url": raw_request.url,
            "headers": dict(raw_request.headers),
            "body": raw_request.body,
        }
    
    def translate_response(self, response: Dict[str, Any]) -> Any:
        """Translate to Cloudflare Response."""
        # This would return a Cloudflare Response object
        # In build output, we generate the appropriate JS
        return response
    
    def get_bindings(self, env: Any) -> Dict[str, Any]:
        """Extract Cloudflare bindings (KV, D1, R2, etc.)."""
        bindings = {}
        if hasattr(env, '__dict__'):
            for key, value in env.__dict__.items():
                if not key.startswith('_'):
                    bindings[key] = value
        return bindings
    
    def generate_entry_point(
        self,
        handler: Callable,
        config: Dict[str, Any],
    ) -> str:
        """Generate Cloudflare Worker entry point."""
        bindings = config.get("bindings", {})
        binding_imports = ", ".join(bindings.keys()) if bindings else ""
        
        return f'''
// Generated by PyNext for Cloudflare Workers
import {{ PyNextHandler }} from './pynext-runtime.js';

export default {{
    async fetch(request, env, ctx) {{
        const handler = new PyNextHandler(env);
        return await handler.handle(request);
    }},
}};
'''
    
    def generate_config(self, config: Dict[str, Any]) -> str:
        """Generate wrangler.toml."""
        name = config.get("name", "pynext-worker")
        main = config.get("main", "dist/_worker.js")
        compatibility_date = config.get("compatibility_date", "2024-01-01")
        
        toml_lines = [
            f'name = "{name}"',
            f'main = "{main}"',
            f'compatibility_date = "{compatibility_date}"',
        ]
        
        # Add KV namespaces
        bindings = config.get("bindings", {})
        if "KV" in bindings:
            toml_lines.extend([
                "",
                "[[kv_namespaces]]",
                f'binding = "{bindings["KV"]}"',
                f'id = "your-kv-namespace-id"  # Replace with actual ID',
            ])
        
        # Add D1 databases
        if "D1" in bindings:
            toml_lines.extend([
                "",
                "[[d1_databases]]",
                f'binding = "{bindings["D1"]}"',
                f'database_name = "your-database"  # Replace with actual name',
                f'database_id = "your-database-id"  # Replace with actual ID',
            ])
        
        return "\n".join(toml_lines)


class VercelAdapter(EdgeAdapter):
    """Adapter for Vercel Edge Functions."""
    
    platform = EdgePlatform.VERCEL
    
    def translate_request(self, raw_request: Any) -> Dict[str, Any]:
        """Translate Vercel Request to standard format."""
        return {
            "method": raw_request.method,
            "url": raw_request.url,
            "headers": dict(raw_request.headers),
            "body": raw_request.body,
        }
    
    def translate_response(self, response: Dict[str, Any]) -> Any:
        """Translate to Vercel Response."""
        return response
    
    def get_bindings(self, env: Any) -> Dict[str, Any]:
        """Vercel uses environment variables for bindings."""
        import os
        return dict(os.environ)
    
    def generate_entry_point(
        self,
        handler: Callable,
        config: Dict[str, Any],
    ) -> str:
        """Generate Vercel Edge Function entry point."""
        return '''
// Generated by PyNext for Vercel Edge Functions
import { PyNextHandler } from './pynext-runtime.js';

export const config = {
    runtime: 'edge',
};

export default async function handler(request) {
    const handler = new PyNextHandler(process.env);
    return await handler.handle(request);
}
'''
    
    def generate_config(self, config: Dict[str, Any]) -> str:
        """Generate vercel.json."""
        import json
        
        vercel_config = {
            "functions": {
                "api/**/*.js": {
                    "runtime": "edge",
                }
            }
        }
        
        return json.dumps(vercel_config, indent=2)


class DenoAdapter(EdgeAdapter):
    """Adapter for Deno Deploy."""
    
    platform = EdgePlatform.DENO
    
    def translate_request(self, raw_request: Any) -> Dict[str, Any]:
        """Translate Deno Request to standard format."""
        return {
            "method": raw_request.method,
            "url": raw_request.url,
            "headers": dict(raw_request.headers),
            "body": raw_request.body,
        }
    
    def translate_response(self, response: Dict[str, Any]) -> Any:
        """Translate to Deno Response."""
        return response
    
    def get_bindings(self, env: Any) -> Dict[str, Any]:
        """Deno uses Deno.env for bindings."""
        return {}
    
    def generate_entry_point(
        self,
        handler: Callable,
        config: Dict[str, Any],
    ) -> str:
        """Generate Deno Deploy entry point."""
        return '''
// Generated by PyNext for Deno Deploy
import { PyNextHandler } from './pynext-runtime.js';

const handler = new PyNextHandler(Deno.env.toObject());

Deno.serve((request) => handler.handle(request));
'''
    
    def generate_config(self, config: Dict[str, Any]) -> str:
        """Generate deno.json."""
        import json
        
        deno_config = {
            "tasks": {
                "start": "deno run --allow-net --allow-env main.ts"
            },
            "imports": {}
        }
        
        return json.dumps(deno_config, indent=2)


class BunAdapter(EdgeAdapter):
    """Adapter for Bun runtime."""
    
    platform = EdgePlatform.BUN
    
    def translate_request(self, raw_request: Any) -> Dict[str, Any]:
        """Translate Bun Request to standard format."""
        return {
            "method": raw_request.method,
            "url": raw_request.url,
            "headers": dict(raw_request.headers),
            "body": raw_request.body,
        }
    
    def translate_response(self, response: Dict[str, Any]) -> Any:
        """Translate to Bun Response."""
        return response
    
    def get_bindings(self, env: Any) -> Dict[str, Any]:
        """Bun uses process.env for bindings."""
        return {}
    
    def generate_entry_point(
        self,
        handler: Callable,
        config: Dict[str, Any],
    ) -> str:
        """Generate Bun entry point."""
        port = config.get("port", 3000)
        
        return f'''
// Generated by PyNext for Bun
import {{ PyNextHandler }} from './pynext-runtime.js';

const handler = new PyNextHandler(process.env);

Bun.serve({{
    port: {port},
    async fetch(request) {{
        return await handler.handle(request);
    }},
}});

console.log('Server running on http://localhost:{port}');
'''
    
    def generate_config(self, config: Dict[str, Any]) -> str:
        """Generate bunfig.toml."""
        return '''
[install]
optional = true

[run]
bun = true
'''


# Adapter registry
_adapters: Dict[EdgePlatform, EdgeAdapter] = {
    EdgePlatform.CLOUDFLARE: CloudflareAdapter(),
    EdgePlatform.VERCEL: VercelAdapter(),
    EdgePlatform.DENO: DenoAdapter(),
    EdgePlatform.BUN: BunAdapter(),
}


def get_adapter(platform: EdgePlatform) -> EdgeAdapter:
    """
    Get adapter for a platform.
    
    Args:
        platform: Target platform
        
    Returns:
        EdgeAdapter instance
        
    Raises:
        ValueError: If platform not supported
    """
    adapter = _adapters.get(platform)
    if not adapter:
        raise ValueError(f"No adapter for platform: {platform}")
    return adapter

